OPTIONS(SKIP=1)

LOAD DATA
INFILE "/u01/clone/BRZL/apps/apps_st/appl/au/12.0.0/bin/XX3_JOURNAL.csv"

REPLACE INTO TABLE CUSTOM_JOURNAL_TBL
FIELDS TERMINATED BY ";"
      
TRAILING NULLCOLS
(
		
USER_JE_SOURCE_NAME,

JE_SOURCE_KEY,
		
DESCRIPTION,
		
JOURNAL_REFERENCE_FLAG,
		
JOURNAL_APPROVAL_FLAG,
		
IMPORT_USING_KEY_FLAG,
		
OVERRIDE_EDITS_FLAG,
		
EFFECTIVE_DATE_RULE_CODE
	
)	